version: '3.8'
services:
  mysql-db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: productdb
    ports:
      - 3307:3306
    restart: always
  springboot-container:
    build: .
    container_name: springboot-container 
    depends_on:
      - mysql-db
    ports:
      - 8080:8080
    restart: always
